name: "🐞 Bug Report"
description: "Report a bug or unexpected behavior in the project"
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the bug clearly and concisely."
      placeholder: "Steps to reproduce, observed behavior, expected behavior..."
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "List steps to reproduce the issue."
      placeholder: "1. Go to ...\n2. Click ...\n3. Observe ..."
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What you expected to happen."
  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened."
  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      options:
        - Low
        - Medium
        - High
