name: "♻️ Refactor"
description: "Request code refactoring or cleanup"
title: "[REFACTOR] "
labels: ["refactor"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the code or module to refactor."
      placeholder: "Which files/modules need refactoring?"
  - type: textarea
    id: reason
    attributes:
      label: "Reason"
      description: "Why should this be refactored?"
  - type: textarea
    id: impact
    attributes:
      label: "Expected Impact"
      description: "How will this improve the project?"
